package com.demo.common.model;

import com.demo.common.model.base.BaseBasicFile;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BasicFile extends BaseBasicFile<BasicFile> {
	public static final BasicFile dao = new BasicFile().dao();
}
