package com.demo.common.model;

import com.demo.common.model.base.BaseQueryCity;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class QueryCity extends BaseQueryCity<QueryCity> {
	public static final QueryCity dao = new QueryCity().dao();
}
